
services:
  nginx:
    container_name: nginx
    build: requirements/nginx/
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - amabrouk-network
    depends_on:
      - wordpress
    restart: always
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    build: requirements/wordpress/
    ports:
        - "9000:9000"
    volumes:
      - wordpress:/var/www/html
    networks:
      - amabrouk-network
    depends_on:
      - mariadb
    restart: always
    env_file:
      - .env

  mariadb:
    container_name: mariadb
    build: requirements/mariadb/
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - amabrouk-network
    restart: always
    env_file:
      - .env

  redis:
    container_name: redis
    build: requirements/bonus/redis/
    networks:
      - amabrouk-network
    depends_on:
      - wordpress
    restart: always
    env_file:
      - .env

  ftp:
    container_name: ftp
    build: requirements/bonus/ftp/
    ports:
      - "21:21"
      - "3000-3009:3000-3009"
    volumes:
      - wordpress:/home/${FTP_USER}/wordpress
    networks:
      - amabrouk-network
    depends_on:
      - wordpress
    restart: always
    env_file:
      - .env

  # adminer:
  #   container_name: adminer
  #   build: requirements/bonus/adminer/
  #   ports:
  #     - "8090:8090"
  #   networks:
  #     - amabrouk-network
  #   depends_on:
  #     - mariadb
  #   restart: always

  # static-site:
  #   container_name: static-site
  #   build: requirements/bonus/static-site/
  #   ports:
  #     - "2005:2005"
  #   networks:
  #     - amabrouk-network
  #   restart: always

  cadvisor:
    container_name: cadvisor
    build: ./requirements/bonus/cadvisor/
    ports:
      - "8080:8080"
    networks:
      - amabrouk-network
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    restart: always

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: /Users/amabrouk/Desktop/Inception/data/wordpress
      o: bind
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      device: /Users/amabrouk/Desktop/Inception/data/mariadb
      o: bind

networks:
  amabrouk-network:
    driver: bridge