
services:
  nginx:
    container_name: nginx
    build: requirements/nginx/
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - amabrouk-network
    depends_on:
      - wordpress
    restart: always
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    build: requirements/wordpress/
    ports:
        - "9000:9000"
    volumes:
      - wordpress:/var/www/html
    networks:
      - amabrouk-network
    depends_on:
      - mariadb
    restart: always
    env_file:
      - .env

  mariadb:
    container_name: mariadb
    build: requirements/mariadb/
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - amabrouk-network
    restart: always
    env_file:
      - .env

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: /Users/amabrouk/Desktop/data/wordpress
      o: bind
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      device: /Users/amabrouk/Desktop/data/mariadb
      o: bind

networks:
  amabrouk-network:
    driver: bridge